#!/usr/bin/env python3
"""
build_bundle.py — CSS Build Pipeline for stock-agent dashboard
==============================================================

Steps:
  1. Concatenate all @import sources → dashboard.bundle.css  (flat, comment-stripped)
  2. Run PurgeCSS  → remove unused selectors (whitelist-safe)
  3. Report size deltas at each step

Usage:
  python build_bundle.py           # full build (concat + purge)
  python build_bundle.py --no-purge  # concat only (faster, for development)
  python build_bundle.py --dry-run   # show what would be purged, don't write

Requirements:
  purgecss CLI must be installed:  npm install -g purgecss

PurgeCSS safelist is maintained in purgecss_safelist.json.
To add new dynamic class patterns, edit that file.
"""

import re
import os
import sys
import json
import shutil
import subprocess
import tempfile

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT   = os.path.dirname(os.path.abspath(__file__))
STATIC      = os.path.join(REPO_ROOT, "src/api/static/dashboard")
CSS_DIR     = os.path.join(STATIC, "css")
BUNDLE_PATH = os.path.join(STATIC, "dashboard.bundle.css")
DASHBOARD   = os.path.join(STATIC, "dashboard.css")
SAFELIST    = os.path.join(REPO_ROOT, "purgecss_safelist.json")

# ── Parse args ────────────────────────────────────────────────────────────────
NO_PURGE  = "--no-purge"  in sys.argv
DRY_RUN   = "--dry-run"   in sys.argv
VERBOSE   = "--verbose"   in sys.argv or "-v" in sys.argv

def log(msg, always=False):
    if always or VERBOSE:
        print(msg)

def size_kb(path):
    return os.path.getsize(path) / 1024

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Bundle — concatenate all @import sources in cascade order
# ─────────────────────────────────────────────────────────────────────────────

def build_bundle():
    print("┌─ Step 1: Concatenate sources ──────────────────────────────────")

    with open(DASHBOARD, encoding="utf-8") as f:
        dashboard_content = f.read()

    # Parse @import order (skip the bundle @import if already present)
    import_re = re.compile(r"@import url\(['\"]?([^'\")\s]+)['\"]?\)", re.IGNORECASE)
    all_imports = import_re.findall(dashboard_content)
    source_imports = [i for i in all_imports if "bundle" not in i]

    print(f"│  Sources: {len(source_imports)} files")

    bundle_parts = [
        "/* dashboard.bundle.css — auto-generated by build_bundle.py */",
        "/* DO NOT EDIT — changes will be overwritten on next build     */",
        f"/* Sources: {len(source_imports)} files | Build: concat + purgecss    */",
        "",
    ]

    total_input = 0

    for import_path in source_imports:
        full_path = os.path.join(STATIC, import_path.lstrip("./"))

        if not os.path.exists(full_path):
            print(f"│  ⚠ NOT FOUND: {full_path}", file=sys.stderr)
            continue

        with open(full_path, encoding="utf-8") as f:
            content = f.read()

        total_input += len(content)

        # Preserve Google Fonts @import (must be at top of output)
        google_fonts = re.findall(
            r"@import url\(['\"]https://[^)]+\)[^;]*;", content
        )

        # Strip local @import lines (not needed in flat bundle)
        content = re.sub(
            r"@import url\(['\"]?(?!https://)[^'\")\s]+['\"]?\)[^;]*;", "", content
        )

        # Strip CSS comments (/* ... */ but NOT /*! ... */ license comments)
        content = re.sub(r"/\*(?!!)(.*?)\*/", "", content, flags=re.DOTALL)

        # Collapse 3+ blank lines → 1
        content = re.sub(r"\n{3,}", "\n\n", content)
        content = content.strip()

        if content or google_fonts:
            fname = import_path.split("/")[-1]
            bundle_parts.append(f"\n/* ── {fname} {'─' * (52 - len(fname))} */")
            for gf in google_fonts:
                bundle_parts.append(gf)
            if content:
                bundle_parts.append(content)

    bundle_content = "\n".join(bundle_parts)
    bundle_content = re.sub(r"\n{3,}", "\n\n", bundle_content)

    if not DRY_RUN:
        with open(BUNDLE_PATH, "w", encoding="utf-8") as f:
            f.write(bundle_content)

    out_kb = len(bundle_content) / 1024
    in_kb  = total_input / 1024
    print(f"│  Input:  {in_kb:.1f} KB ({len(source_imports)} files)")
    print(f"│  Output: {out_kb:.1f} KB  (saved {in_kb - out_kb:.1f} KB via comment stripping)")
    print(f"└─ Bundle written: dashboard.bundle.css")
    return len(bundle_content)


# ─────────────────────────────────────────────────────────────────────────────
# STEP 2: PurgeCSS — remove unused selectors
# ─────────────────────────────────────────────────────────────────────────────

def build_safelist_args():
    """Read purgecss_safelist.json and build purgecss CLI safelist flags."""
    if not os.path.exists(SAFELIST):
        print("⚠ purgecss_safelist.json not found — running without safelist", file=sys.stderr)
        return []

    with open(SAFELIST, encoding="utf-8") as f:
        config = json.load(f)

    args = []

    # Static safelist
    static = config.get("safelist", {}).get("standard", [])
    if static:
        # PurgeCSS CLI doesn't support long safelist via args well — write temp config
        pass  # handled via config file below

    return static, config.get("safelistPatterns", [])


def run_purgecss():
    print("┌─ Step 2: PurgeCSS — remove unused selectors ───────────────────")

    # Check purgecss is available
    purgecss_bin = shutil.which("purgecss")
    if not purgecss_bin:
        print("│  ⚠ purgecss not found in PATH — skipping purge step")
        print("│    Install with: npm install -g purgecss")
        print("└─ Skipped")
        return None

    before_kb = size_kb(BUNDLE_PATH)

    # Read safelist
    if not os.path.exists(SAFELIST):
        print(f"│  ⚠ {SAFELIST} not found")
        static_list, patterns = [], []
    else:
        with open(SAFELIST, encoding="utf-8") as f:
            sl_config = json.load(f)
        static_list = sl_config.get("safelist", {}).get("standard", [])
        patterns    = sl_config.get("safelistPatterns", [])

    # Write a temporary PurgeCSS config file
    # (CLI config supports full JS-style config via .js, but JSON via --config is limited)
    # We use a temp JS config file for full safelist support
    # Build greedy patterns as proper JS RegExp literals
    regex_items = ",\n    ".join(f"/{p}/" for p in patterns)
    static_json = json.dumps(static_list, indent=4)
    purge_config_js = f"""module.exports = {{
  content: [
    "{STATIC}/**/*.html",
    "{STATIC}/**/*.js"
  ],
  css: ["{BUNDLE_PATH}"],
  output: "{STATIC}/",
  safelist: {{
    standard: {static_json},
    greedy: [
    {regex_items}
    ],
    keyframes: true,
    variables: true,
  }}
}};
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".js",
                                     delete=False, encoding="utf-8") as tmp:
        tmp.write(purge_config_js)
        tmp_config = tmp.name

    print(f"│  Bundle before: {before_kb:.1f} KB")
    print(f"│  Safelist: {len(static_list)} exact classes, {len(patterns)} patterns")

    if DRY_RUN:
        print("│  [DRY RUN] Would run purgecss — skipping write")
        os.unlink(tmp_config)
        print("└─ Dry run complete")
        return None

    # Run PurgeCSS
    cmd = [purgecss_bin, "--config", tmp_config]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    os.unlink(tmp_config)

    if result.returncode != 0:
        print(f"│  ✗ PurgeCSS failed:\n{result.stderr}", file=sys.stderr)
        print("└─ Purge failed — bundle unchanged")
        return None

    after_kb = size_kb(BUNDLE_PATH)
    saved_kb = before_kb - after_kb
    pct      = (saved_kb / before_kb * 100) if before_kb > 0 else 0

    print(f"│  Bundle after:  {after_kb:.1f} KB")
    print(f"│  Purged:        {saved_kb:.1f} KB  ({pct:.1f}% removed)")

    if result.stderr:
        log(f"│  purgecss stderr: {result.stderr[:200]}")

    print("└─ PurgeCSS complete")
    return after_kb


# ─────────────────────────────────────────────────────────────────────────────
# STEP 3: Summary report
# ─────────────────────────────────────────────────────────────────────────────

def print_summary(bundle_bytes, after_kb):
    bundle_kb = bundle_bytes / 1024
    print()
    print("╔══════════════════════════════════════════════════════════════╗")
    print("║  CSS Build Summary                                           ║")
    print("╠══════════════════════════════════════════════════════════════╣")
    print(f"║  After concat:   {bundle_kb:>7.1f} KB                               ║")
    if after_kb:
        final_kb = after_kb
        print(f"║  After purge:    {final_kb:>7.1f} KB  ({bundle_kb - final_kb:.1f} KB removed)            ║")
    else:
        final_kb = bundle_kb
    print(f"║  Final bundle:   {final_kb:>7.1f} KB  → dashboard.bundle.css         ║")
    print("╠══════════════════════════════════════════════════════════════╣")
    print("║  To rebuild after CSS changes:                               ║")
    print("║    python build_bundle.py           # full build             ║")
    print("║    python build_bundle.py --no-purge # concat only           ║")
    print("╚══════════════════════════════════════════════════════════════╝")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print()
    print("▶ stock-agent CSS Build Pipeline")
    print(f"  Mode: {'dry-run' if DRY_RUN else ('concat-only' if NO_PURGE else 'full')}")
    print()

    bundle_bytes = build_bundle()

    after_kb = None
    if not NO_PURGE and not DRY_RUN:
        after_kb = run_purgecss()
    elif NO_PURGE:
        print("  [--no-purge] Skipping PurgeCSS step")

    print_summary(bundle_bytes, after_kb)
